import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './components/navbar/NavBar'
import Footer from './components/footer/Footer'
import CartProvider from '@/provider/CartProvider'
import { Toaster } from 'react-hot-toast'
import Category from './components/home/Category'
import Head from 'next/head'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Satis.com',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
      <style>
        {`

          @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@200;300;400;500&display=swap');
          body {
            font-family: 'Plus Jakarta Sans', sans-serif;
          }
          
        `}
      </style>
      

      </Head>
      <body className={inter.className}>
        
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
        <CartProvider>
          <div className='flex flex-col min-h-screen'>
            <NavBar />
            <Category />

            <main className='flex-grow '>{children}  </main>
            
            <Footer />
          </div>
        </CartProvider>
      </body>
    </html>
  )
}
